"""Currency

Revision ID: 4c9beb3fb76a
Revises: 83c08dacd132
Create Date: 2019-04-04 19:37:13.181922

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c9beb3fb76a'
down_revision = '83c08dacd132'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Currency',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=140), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Currency')
    # ### end Alembic commands ###
