"""preamble

Revision ID: c4a74b30bde5
Revises: e6f825343b4f
Create Date: 2019-04-18 17:46:42.622532

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4a74b30bde5'
down_revision = 'e6f825343b4f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('preamble_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'preamble_id')
    # ### end Alembic commands ###
